[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
send_message = '0xbe3af806cfc418404e72112f6565f0f183765d804358c8e79beff01a47121e24'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]